//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplication
    {
        public Aplication()
        {
            this.Groups = new HashSet<Group>();
            this.Elements = new HashSet<Element>();
            this.Roles = new HashSet<Role>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Element> Elements { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
