//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Roles = new HashSet<Role>();
            this.UserDomains = new HashSet<UserDomain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public string Aplication_Id { get; set; }
    
        public virtual Aplication Aplication { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<UserDomain> UserDomains { get; set; }
    }
}
